"""empty message

Revision ID: 968f6bc006c2
Revises: ac17ce297e66
Create Date: 2022-08-11 06:42:20.227135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968f6bc006c2'
down_revision = 'ac17ce297e66'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('shorten_url_created_by', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_urls_shorten_url'), 'urls', ['shorten_url'], unique=False)
    op.create_index(op.f('ix_urls_shorten_url_created_by'), 'urls', ['shorten_url_created_by'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_shorten_url_created_by'), table_name='urls')
    op.drop_index(op.f('ix_urls_shorten_url'), table_name='urls')
    op.drop_column('urls', 'shorten_url_created_by')
    # ### end Alembic commands ###
    pass
