"""empty message

Revision ID: ac17ce297e66
Revises: ab7d407452aa
Create Date: 2022-07-15 16:05:43.616307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac17ce297e66'
down_revision = 'ab7d407452aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('is_public', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'is_public')
    # ### end Alembic commands ###
