"""empty message

Revision ID: d75855faf152
Revises: 
Create Date: 2020-04-08 16:59:24.963059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75855faf152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_url', sa.String(length=256), nullable=True),
    sa.Column('shorten_url', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shorten_url')
    )
    op.create_index(op.f('ix_urls_origin_url'), 'urls', ['origin_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_origin_url'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
